from src.catalogs.scenario_config import ScenarioConfig

SCENARIO_CATALOG = {
    'withdrawal_rate': ScenarioConfig(
        scenario_id='withdrawal_rate',
        scenario_name='All Account Types, Fixed Rate',
        withdrawal_mode='fixed_rate',
        montecarlo_id='mc_rate',
        include_dashboard=True,
        tax_deferred_notes="RMDs may force withdrawals beyond the fixed rate %. All withdrawals are taxable as ordinary income.",
        taxable_notes="Distinguishes ordinary income from capital gains and qualified dividends. Uses standard deduction, AMT, and tax-loss harvesting.",
        tax_free_notes="Qualified withdrawals are tax-free. No RMDs.",
        pros="Simple.",
        cons="Does not optimize across account types.",
        key_concepts="Withdraws a fixed % annually, adjusted for inflation. Accounts expected to deplete in ~30 years.",
    ),
    'withdrawal_amount': ScenarioConfig(
        scenario_id='withdrawal_amount',
        scenario_name='Tax Smart, Target Amount',
        withdrawal_mode='fixed_amount',
        montecarlo_id='mc_amount',
        include_dashboard=True,
        tax_deferred_notes="RMDs are delayed until RMD age. Taxed as ordinary income.",
        taxable_notes="Withdraws target amount minus RMDs. Handles capital gains and qualified dividends using tax optimization strategies.",
        tax_free_notes="Withdrawals delayed until other accounts are depleted. No RMDs.",
        pros="Optimizes across account types.",
        cons="May trigger capital gains and reduce annual compounding in taxable accounts.",
        key_concepts="Inflation-adjusted target withdrawals pulled in order: Taxable → Tax-Deferred → Tax-Free.",
    ),
    'withdrawal_guardrail': ScenarioConfig(
        scenario_id='withdrawal_guardrail',
        scenario_name='Tax Smart, Target Amount w/Guardrails',
        withdrawal_mode='guardrail',
        montecarlo_id='mc_guardrail',
        include_dashboard=True,
        tax_deferred_notes="Similar to fixed amount. RMDs delayed and taxed.",
        taxable_notes="Withdrawals capped by guardrails. Prioritizes tax optimization.",
        tax_free_notes="Used only after other accounts are exhausted.",
        pros="Balances stability with flexibility.",
        cons="Triggers capital gains and slows taxable account growth.",
        tips="Can use inflation and market guardrails to adjust withdrawals dynamically.",
    ),
    'roth_conversion': ScenarioConfig(
        scenario_id='roth_conversion',
        scenario_name='Tax Smart, Roth Conversion',
        withdrawal_mode='fixed_amount',
        montecarlo_id='mc_roth_conversion',
        include_dashboard=True,
        tax_deferred_notes="Maximizes withdrawals to stay under target tax brackets. Converted amounts taxed as ordinary income.",
        taxable_notes="Handles taxes on conversion amount and gap from bracket targeting.",
        tax_free_notes="Withdrawals delayed until other accounts are exhausted. No RMDs.",
        pros="Minimizes future taxes and boosts tax-free compounding.",
        cons="Converted amounts locked for 5 years. Conversion is taxed.",
        tips="Convert early (before Social Security/RMDs). Offset taxes with deductions or market timing.",
    ),
}
